# Generated by Django 5.2.1 on 2025-09-09 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('display_name', models.CharField(help_text='Nombre para mostrar en la interfaz', max_length=120)),
                ('avatar_url', models.CharField(blank=True, help_text='URL del avatar del usuario', max_length=512, null=True)),
                ('locale', models.CharField(blank=True, help_text='Configuración regional del usuario', max_length=16, null=True)),
                ('user', models.OneToOneField(help_text='Usuario asociado al perfil', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_user_profile')],
            },
        ),
    ]
