version: '3.9'

services:
  backend:
    build: .
    container_name: django_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8000

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always