# Generated by Django 5.2.6 on 2025-09-10 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modeling', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(help_text='Momento de inicio de la sesión')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Momento de finalización de la sesión', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Metadatos adicionales de la sesión', null=True)),
                ('diagram', models.ForeignKey(help_text='Diagrama siendo editado colaborativamente', on_delete=django.db.models.deletion.RESTRICT, to='modeling.diagram')),
                ('started_by', models.ForeignKey(help_text='Usuario que inició la sesión', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de borrado lógico', null=True)),
                ('body', models.TextField(help_text='Contenido del comentario')),
                ('target_type', models.CharField(help_text='Tipo de elemento al que se ancla', max_length=32)),
                ('target_id', models.UUIDField(help_text='ID del elemento al que se ancla')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del comentario')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('author', models.ForeignKey(help_text='Autor del comentario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(blank=True, help_text='Diagrama específico (opcional)', null=True, on_delete=django.db.models.deletion.RESTRICT, to='modeling.diagram')),
                ('parent', models.ForeignKey(blank=True, help_text='Comentario padre (para hilos)', null=True, on_delete=django.db.models.deletion.RESTRICT, to='collaboration.comment')),
                ('project', models.ForeignKey(help_text='Proyecto que contiene el comentario', on_delete=django.db.models.deletion.RESTRICT, to='workspace.project')),
            ],
            options={
                'indexes': [models.Index(fields=['diagram', 'target_type', 'target_id'], name='collaborati_diagram_ffd7dc_idx'), models.Index(fields=['parent'], name='collaborati_parent__9d3968_idx')],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('last_seen_at', models.DateTimeField(help_text='Última actividad del usuario')),
                ('cursor', models.JSONField(blank=True, help_text='Posición del cursor/selección del usuario', null=True)),
                ('session', models.ForeignKey(help_text='Sesión colaborativa', on_delete=django.db.models.deletion.RESTRICT, to='collaboration.collabsession')),
                ('user', models.ForeignKey(help_text='Usuario presente en la sesión', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'user'), name='unique_session_user_presence')],
            },
        ),
    ]
