# Generated by Django 5.2.1 on 2025-09-12 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        ('modeling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('locked_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se adquirió el bloqueo')),
                ('expires_at', models.DateTimeField(help_text='Momento en que expira el bloqueo')),
                ('purpose', models.CharField(default='editing', help_text='Propósito del bloqueo (editing, reviewing, etc.)', max_length=100)),
                ('diagram', models.OneToOneField(help_text='Diagrama bloqueado', on_delete=django.db.models.deletion.CASCADE, to='modeling.diagram')),
                ('locked_by', models.ForeignKey(help_text='Usuario que posee el bloqueo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['diagram'], name='collaborati_diagram_028674_idx'), models.Index(fields=['locked_by'], name='collaborati_locked__e2c660_idx'), models.Index(fields=['expires_at'], name='collaborati_expires_724f07_idx')],
            },
        ),
    ]
