# Generated by Django 5.2.1 on 2025-09-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_lock'),
    ]

    operations = [
    ]
