# Generated by Django 5.2.6 on 2025-09-10 15:28

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modeling', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('provider', models.CharField(help_text='Proveedor de almacenamiento (S3, GCS, LOCAL)', max_length=16)),
                ('bucket', models.CharField(help_text='Bucket o contenedor de almacenamiento', max_length=128)),
                ('object_key', models.CharField(help_text='Clave o ruta del objeto', max_length=512)),
                ('size_bytes', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('content_type', models.CharField(blank=True, help_text='Tipo MIME del contenido', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la referencia')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la plantilla', max_length=120)),
                ('language_target', models.CharField(help_text='Lenguaje/framework objetivo (ej. SPRING_BOOT)', max_length=32)),
                ('version', models.CharField(help_text='Versión de la plantilla', max_length=20)),
                ('config', models.JSONField(help_text='Configuración de la plantilla')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la plantilla')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'language_target', 'version'), name='unique_template_name_lang_version')],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'En cola'), ('RUNNING', 'Ejecutando'), ('SUCCEEDED', 'Exitoso'), ('FAILED', 'Fallido')], help_text='Estado actual del trabajo', max_length=16)),
                ('started_at', models.DateTimeField(help_text='Momento de inicio del trabajo')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Momento de finalización del trabajo', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la generación falló', null=True)),
                ('output_path', models.CharField(blank=True, help_text='Ruta del código generado', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Metadatos del proceso de generación', null=True)),
                ('metrics', models.JSONField(blank=True, help_text='Métricas del proceso de generación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del trabajo')),
                ('diagram_version', models.ForeignKey(help_text='Versión específica del diagrama a usar', on_delete=django.db.models.deletion.RESTRICT, to='modeling.diagramversion')),
                ('project', models.ForeignKey(help_text='Proyecto para el cual se genera código', on_delete=django.db.models.deletion.RESTRICT, to='workspace.project')),
                ('requester', models.ForeignKey(help_text='Usuario que solicitó la generación', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Plantilla de generación utilizada', on_delete=django.db.models.deletion.RESTRICT, to='generation.template')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('level', models.CharField(help_text='Nivel del log (INFO, WARN, ERROR, etc.)', max_length=16)),
                ('message', models.TextField(help_text='Mensaje del log')),
                ('ts', models.DateTimeField(help_text='Timestamp del mensaje')),
                ('job', models.ForeignKey(help_text='Trabajo asociado al log', on_delete=django.db.models.deletion.CASCADE, to='generation.generationjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'ts'], name='generation__job_id_cc846b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ZIP_BACKEND', 'Backend comprimido'), ('SWAGGER_JSON', 'Especificación Swagger JSON'), ('SWAGGER_YAML', 'Especificación Swagger YAML'), ('SQL_SCRIPTS', 'Scripts SQL')], help_text='Tipo de artefacto', max_length=16)),
                ('filename', models.CharField(help_text='Nombre del archivo o directorio', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Contenido del artefacto (para archivos pequeños)', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Metadatos adicionales del artefacto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del artefacto')),
                ('job', models.ForeignKey(help_text='Trabajo que produjo este artefacto', on_delete=django.db.models.deletion.CASCADE, to='generation.generationjob')),
                ('storage_ref', models.ForeignKey(blank=True, help_text='Referencia de almacenamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.storageref')),
            ],
            options={
                'indexes': [models.Index(fields=['job'], name='generation__job_id_a4d39f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SwaggerSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('spec_json', models.JSONField(help_text='Especificación OpenAPI en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la especificación')),
                ('job', models.OneToOneField(help_text='Trabajo que generó esta especificación', on_delete=django.db.models.deletion.CASCADE, to='generation.generationjob')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['spec_json'], name='generation__spec_js_ea81e1_gin')],
            },
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['project', 'status'], name='generation__project_b966c9_idx'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['diagram_version'], name='generation__diagram_426390_idx'),
        ),
    ]
