# Generated by Django 5.2.1 on 2025-09-09 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de borrado lógico', null=True)),
                ('name', models.CharField(help_text='Nombre de la organización', max_length=120)),
                ('slug', models.CharField(help_text='Identificador único legible para URLs', max_length=80, unique=True)),
                ('plan', models.CharField(blank=True, help_text='Plan de suscripción de la organización', max_length=32, null=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la organización', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('email', models.CharField(help_text='Correo del usuario invitado', max_length=255)),
                ('role', models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('EDITOR', 'Editor'), ('VIEWER', 'Visualizador')], help_text='Rol propuesto para el invitado', max_length=10)),
                ('token', models.CharField(help_text='Token único de la invitación', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración de la invitación')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la invitación')),
                ('accepted_by', models.ForeignKey(blank=True, help_text='Usuario que aceptó la invitación', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organización que envía la invitación', on_delete=django.db.models.deletion.RESTRICT, to='workspace.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de borrado lógico', null=True)),
                ('name', models.CharField(help_text='Nombre del proyecto', max_length=120)),
                ('key', models.CharField(help_text='Clave corta del proyecto', max_length=16)),
                ('description', models.TextField(blank=True, help_text='Descripción del proyecto', null=True)),
                ('is_private', models.BooleanField(default=False, help_text='Si el proyecto es privado')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el proyecto', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organización propietaria del proyecto', on_delete=django.db.models.deletion.RESTRICT, to='workspace.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('EDITOR', 'Editor'), ('VIEWER', 'Visualizador')], help_text='Rol del usuario en el proyecto', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de adición al proyecto')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece', on_delete=django.db.models.deletion.RESTRICT, to='workspace.project')),
                ('user', models.ForeignKey(help_text='Usuario miembro del proyecto', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('role', models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('EDITOR', 'Editor'), ('VIEWER', 'Visualizador')], help_text='Rol del usuario en la organización', max_length=10)),
                ('status', models.CharField(choices=[('INVITED', 'Invitado'), ('ACTIVE', 'Activo')], help_text='Estado de la membresía', max_length=10)),
                ('user', models.ForeignKey(help_text='Usuario miembro', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organización a la que pertenece', on_delete=django.db.models.deletion.RESTRICT, to='workspace.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='workspace_m_organiz_9cc566_idx'), models.Index(fields=['user'], name='workspace_m_user_id_d49e9f_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_user')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization'], name='workspace_p_organiz_4d0e35_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='unique_organization_project_key'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project'], name='workspace_p_project_ef013e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user'], name='workspace_p_user_id_3db060_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_user'),
        ),
    ]
